"""Association Rule model for recommendations."""

from sqlalchemy import Column, Float, DateTime, ForeignKey
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import relationship
import uuid
from datetime import datetime, timezone

from app.core.database import Base


class AssociationRule(Base):
    """
    Stores association rules generated by Apriori/FP-Growth.
    Represents the rule: {antecedent} -> {consequent}
    """
    __tablename__ = "association_rules"
    
    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4, index=True)
    
    # The item(s) already in the cart (We simplify by assuming 1-to-1 rules for performance)
    antecedent_id = Column(UUID(as_uuid=True), ForeignKey("books.id", ondelete="CASCADE"), nullable=False, index=True)
    
    # The recommended item
    consequent_id = Column(UUID(as_uuid=True), ForeignKey("books.id", ondelete="CASCADE"), nullable=False, index=True)
    
    # Apriori metrics
    support = Column(Float, nullable=False)
    confidence = Column(Float, nullable=False)
    lift = Column(Float, nullable=False, index=True) # Index on lift for sorting
    
    created_at = Column(DateTime(timezone=True), default=lambda: datetime.now(timezone.utc))
    
    # Relationships
    antecedent_book = relationship("Book", foreign_keys=[antecedent_id])
    consequent_book = relationship("Book", foreign_keys=[consequent_id])
    
    def __repr__(self):
        return f"<AssociationRule(antecedent={self.antecedent_id}, consequent={self.consequent_id}, lift={self.lift})>"
