"""Add AssociationRule

Revision ID: b80f60697e7e
Revises: fda5bb16d41c
Create Date: 2026-04-08 23:59:06.319648

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b80f60697e7e'
down_revision: Union[str, Sequence[str], None] = 'fda5bb16d41c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_review_user_book', 'reviews', ['user_id', 'book_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_review_user_book', 'reviews', type_='unique')
    # ### end Alembic commands ###
