"""Add Review model

Revision ID: f65e3775a3dd
Revises: 2fd626caa00a
Create Date: 2026-02-21 14:44:17.358293

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f65e3775a3dd'
down_revision: Union[str, Sequence[str], None] = '2fd626caa00a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_books_genres_gin'), table_name='books', postgresql_using='gin')
    op.drop_index(op.f('idx_books_stock_price'), table_name='books', postgresql_where='(stock > 0)')
    op.drop_index(op.f('idx_user_connections_score'), table_name='user_connections')
    op.drop_index(op.f('idx_user_interactions_created_at'), table_name='user_interactions')
    op.drop_index(op.f('idx_user_interactions_type'), table_name='user_interactions')
    op.drop_index(op.f('idx_user_interactions_user_book'), table_name='user_interactions')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_user_interactions_user_book'), 'user_interactions', ['user_id', 'book_id'], unique=False)
    op.create_index(op.f('idx_user_interactions_type'), 'user_interactions', ['interaction_type'], unique=False)
    op.create_index(op.f('idx_user_interactions_created_at'), 'user_interactions', [sa.literal_column('created_at DESC')], unique=False)
    op.create_index(op.f('idx_user_connections_score'), 'user_connections', [sa.literal_column('compatibility_score DESC')], unique=False)
    op.create_index(op.f('idx_books_stock_price'), 'books', ['stock', 'price'], unique=False, postgresql_where='(stock > 0)')
    op.create_index(op.f('idx_books_genres_gin'), 'books', ['genres'], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###
