// ── BiblioMind Social — Mock Data ──
// Uses realistic book-community data. User IDs reference the main app's auth system.

import {
    Community,
    CommunityPost,
    CommunityMember,
    RecentActivity,
} from "@/types/social";

// ─── Mock Members ───
const MOCK_MEMBERS: CommunityMember[] = [
    { user_id: "1", full_name: "Ahmet Yılmaz", role: "creator", joined_at: "2025-12-01T10:00:00Z" },
    { user_id: "2", full_name: "Elif Demir", role: "admin", joined_at: "2025-12-05T12:00:00Z" },
    { user_id: "3", full_name: "Mehmet Kaya", role: "moderator", joined_at: "2025-12-10T08:00:00Z" },
    { user_id: "4", full_name: "Zeynep Arslan", role: "member", joined_at: "2025-12-15T14:00:00Z" },
    { user_id: "5", full_name: "Can Öztürk", role: "member", joined_at: "2025-12-20T09:00:00Z" },
    { user_id: "6", full_name: "Selin Çelik", role: "member", joined_at: "2026-01-02T11:00:00Z" },
    { user_id: "7", full_name: "Burak Şahin", role: "member", joined_at: "2026-01-05T16:00:00Z" },
    { user_id: "8", full_name: "Deniz Aydın", role: "moderator", joined_at: "2026-01-10T13:00:00Z" },
    { user_id: "9", full_name: "Ayşe Koç", role: "member", joined_at: "2026-01-15T07:00:00Z" },
    { user_id: "10", full_name: "Emre Yıldız", role: "member", joined_at: "2026-01-20T10:00:00Z" },
    { user_id: "11", full_name: "Fatma Erdoğan", role: "member", joined_at: "2026-02-01T15:00:00Z" },
    { user_id: "12", full_name: "Hakan Polat", role: "member", joined_at: "2026-02-05T12:00:00Z" },
];

// ─── Mock Communities ───
export const MOCK_COMMUNITIES: Community[] = [
    {
        id: "comm-1",
        name: "Lord of the Rings Lovers",
        description:
            "A community for fans of J.R.R. Tolkien's epic masterpiece. Discuss the books, the lore, the languages, and everything Middle-earth. From the Shire to Mordor, share your journey through Tolkien's world.",
        profile_photo: "/lotr.png",
        banner_photo: "https://images.unsplash.com/photo-1618519764620-7403abdbdfe9?w=1200&h=400&fit=crop",
        category_tags: ["Fantasy", "Classics", "Adventure"],
        privacy: "public",
        rules: [
            "No spoilers without spoiler tags",
            "Be respectful to all members",
            "Stay on topic — Tolkien & Middle-earth only",
            "No self-promotion or spam",
            "Credit fan art to original creators",
        ],
        related_books: [
            { title: "The Fellowship of the Ring", author: "J.R.R. Tolkien" },
            { title: "The Two Towers", author: "J.R.R. Tolkien" },
            { title: "The Return of the King", author: "J.R.R. Tolkien" },
            { title: "The Silmarillion", author: "J.R.R. Tolkien" },
        ],
        website: "https://tolkiensociety.org",
        location: "Worldwide",
        creator_id: "1",
        creator_name: "Ahmet Yılmaz",
        member_count: 1284,
        post_count: 342,
        members: MOCK_MEMBERS.slice(0, 8),
        created_at: "2025-12-01T10:00:00Z",
        is_member: true,
        is_creator: false,
    },
    {
        id: "comm-2",
        name: "Potterheads United",
        description:
            "Welcome to the Wizarding World! Whether you're Gryffindor, Slytherin, Ravenclaw, or Hufflepuff — this is your common room. Discuss theories, share fan art, and relive the magic of Harry Potter.",
        profile_photo: "/hp.png",
        banner_photo: "https://images.unsplash.com/photo-1551269901-5c5e14c25df7?w=1200&h=400&fit=crop",
        category_tags: ["Fantasy", "Young Adult", "Adventure"],
        privacy: "public",
        rules: [
            "Use spoiler tags for Cursed Child discussions",
            "No gatekeeping — all fans welcome",
            "Keep debates civil",
            "No piracy or unofficial downloads",
        ],
        related_books: [
            { title: "Harry Potter and the Sorcerer's Stone", author: "J.K. Rowling" },
            { title: "Harry Potter and the Deathly Hallows", author: "J.K. Rowling" },
            { title: "Fantastic Beasts and Where to Find Them", author: "J.K. Rowling" },
        ],
        creator_id: "2",
        creator_name: "Elif Demir",
        member_count: 2156,
        post_count: 567,
        members: MOCK_MEMBERS.slice(1, 10),
        created_at: "2025-11-15T08:00:00Z",
        is_member: true,
        is_creator: false,
    },
    {
        id: "comm-3",
        name: "Dune Universe",
        description:
            "Fear is the mind-killer. Explore the deserts of Arrakis, the politics of the Imperium, and the philosophy of Frank Herbert's Dune saga. Spice must flow!",
        profile_photo: "https://images.unsplash.com/photo-1509316785289-025f5b846b35?w=200&h=200&fit=crop",
        banner_photo: "https://images.unsplash.com/photo-1509316785289-025f5b846b35?w=1200&h=400&fit=crop",
        category_tags: ["Science Fiction", "Philosophy", "Adventure"],
        privacy: "public",
        rules: [
            "Tag spoilers for books beyond the original Dune",
            "Respect different interpretations",
            "No movie-only discussions in book threads",
        ],
        related_books: [
            { title: "Dune", author: "Frank Herbert" },
            { title: "Dune Messiah", author: "Frank Herbert" },
            { title: "Children of Dune", author: "Frank Herbert" },
        ],
        creator_id: "3",
        creator_name: "Mehmet Kaya",
        member_count: 876,
        post_count: 198,
        members: MOCK_MEMBERS.slice(2, 9),
        created_at: "2026-01-10T14:00:00Z",
        is_member: false,
        is_creator: false,
    },
    {
        id: "comm-4",
        name: "Crime & Thriller Book Club",
        description:
            "For those who love a good mystery. Share your favourite whodunits, discuss plot twists, and recommend the darkest thrillers. Warning: may contain spoilers behind tags!",
        profile_photo: "https://images.unsplash.com/photo-1587876931567-564ad825dc08?w=200&h=200&fit=crop",
        banner_photo: "https://images.unsplash.com/photo-1587876931567-564ad825dc08?w=1200&h=400&fit=crop",
        category_tags: ["Crime", "Thriller", "Mystery"],
        privacy: "public",
        rules: [
            "ALWAYS use spoiler tags",
            "No real-crime content",
            "Keep recommendations family-friendly unless tagged",
        ],
        related_books: [
            { title: "Gone Girl", author: "Gillian Flynn" },
            { title: "The Girl with the Dragon Tattoo", author: "Stieg Larsson" },
            { title: "In the Woods", author: "Tana French" },
        ],
        creator_id: "4",
        creator_name: "Zeynep Arslan",
        member_count: 654,
        post_count: 145,
        members: MOCK_MEMBERS.slice(3, 11),
        created_at: "2026-02-01T09:00:00Z",
        is_member: false,
        is_creator: false,
    },
    {
        id: "comm-5",
        name: "Classic Literature Society",
        description:
            "A refined gathering for lovers of timeless literature. From Dostoevsky to Austen, from Homer to Kafka — explore the works that shaped humanity's greatest stories.",
        profile_photo: "/nutuk.png",
        banner_photo: "https://images.unsplash.com/photo-1481627834876-b7833e8f5570?w=1200&h=400&fit=crop",
        category_tags: ["Classics", "Fiction", "Philosophy", "History"],
        privacy: "private",
        rules: [
            "Academic tone preferred but not required",
            "Cite sources when sharing analysis",
            "Monthly reading assignments are optional but encouraged",
            "Respect all cultural perspectives",
        ],
        related_books: [
            { title: "Crime and Punishment", author: "Fyodor Dostoevsky" },
            { title: "Pride and Prejudice", author: "Jane Austen" },
            { title: "The Great Gatsby", author: "F. Scott Fitzgerald" },
        ],
        website: "https://classiclit.org",
        creator_id: "5",
        creator_name: "Can Öztürk",
        member_count: 432,
        post_count: 89,
        members: MOCK_MEMBERS.slice(4, 12),
        created_at: "2026-01-20T11:00:00Z",
        is_member: false,
        is_creator: false,
    },
    {
        id: "comm-6",
        name: "Sci-Fi Universe",
        description:
            "Beam me up! From hard sci-fi to space opera, cyberpunk to post-apocalyptic — if it's set in the future or in space, we're reading it. Discuss, debate, and discover the best science fiction.",
        profile_photo: "https://images.unsplash.com/photo-1446776811953-b23d57bd21aa?w=200&h=200&fit=crop",
        banner_photo: "https://images.unsplash.com/photo-1446776811953-b23d57bd21aa?w=1200&h=400&fit=crop",
        category_tags: ["Science Fiction", "Dystopia", "Adventure"],
        privacy: "public",
        rules: [
            "Be inclusive of all sub-genres",
            "No elitism — all reading levels welcome",
            "Spoiler tags are mandatory",
        ],
        related_books: [
            { title: "Neuromancer", author: "William Gibson" },
            { title: "The Left Hand of Darkness", author: "Ursula K. Le Guin" },
            { title: "Ender's Game", author: "Orson Scott Card" },
        ],
        creator_id: "6",
        creator_name: "Selin Çelik",
        member_count: 1023,
        post_count: 276,
        members: MOCK_MEMBERS.slice(0, 7),
        created_at: "2025-12-25T16:00:00Z",
        is_member: true,
        is_creator: false,
    },
];

// ─── Mock Posts ───
export const MOCK_POSTS: CommunityPost[] = [
    {
        id: "post-1",
        community_id: "comm-1",
        community_name: "Lord of the Rings Lovers",
        author_id: "1",
        author_name: "Ahmet Yılmaz",
        author_role: "creator",
        content:
            "Just finished re-reading The Silmarillion for the third time and I still discover new connections to the main trilogy. The story of Beren and Lúthien is arguably the most beautiful love story ever written. What's your favourite chapter?",
        created_at: "2026-04-23T14:30:00Z",
        likes: 47,
        comments: [
            {
                id: "cmt-1",
                author_id: "4",
                author_name: "Zeynep Arslan",
                content: "Beren and Lúthien is incredible! But I have a soft spot for the Fall of Gondolin.",
                created_at: "2026-04-23T15:00:00Z",
                likes: 12,
            },
            {
                id: "cmt-2",
                author_id: "5",
                author_name: "Can Öztürk",
                content: "The Ainulindalë (the creation myth) blows my mind every single time. Tolkien was a genius.",
                created_at: "2026-04-23T15:30:00Z",
                likes: 8,
            },
        ],
        saves: 15,
        is_liked: true,
        is_saved: false,
    },
    {
        id: "post-2",
        community_id: "comm-2",
        community_name: "Potterheads United",
        author_id: "2",
        author_name: "Elif Demir",
        author_role: "creator",
        content:
            "Hot take: The Prisoner of Azkaban is the best book in the series, not because of the plot twists, but because it's the last book where Harry gets to just be a kid at Hogwarts. The time-turner sequence is pure literary magic.",
        image_url: "https://images.unsplash.com/photo-1618519764620-7403abdbdfe9?w=800&h=500&fit=crop",
        created_at: "2026-04-23T12:00:00Z",
        likes: 89,
        comments: [
            {
                id: "cmt-3",
                author_id: "6",
                author_name: "Selin Çelik",
                content: "Agreed 100%! Also, Lupin is the best Defence Against the Dark Arts teacher by far.",
                created_at: "2026-04-23T12:45:00Z",
                likes: 23,
            },
        ],
        saves: 32,
        is_liked: false,
        is_saved: true,
    },
    {
        id: "post-3",
        community_id: "comm-1",
        community_name: "Lord of the Rings Lovers",
        author_id: "3",
        author_name: "Mehmet Kaya",
        author_role: "moderator",
        content:
            "📚 This week's discussion: If you could visit any location in Middle-earth, where would you go and why? I'd choose Rivendell — the Last Homely House sounds like paradise for book lovers!",
        created_at: "2026-04-22T18:00:00Z",
        likes: 63,
        comments: [
            {
                id: "cmt-4",
                author_id: "7",
                author_name: "Burak Şahin",
                content: "The Shire, no question. Second breakfast is calling my name 🍳",
                created_at: "2026-04-22T18:30:00Z",
                likes: 31,
            },
            {
                id: "cmt-5",
                author_id: "8",
                author_name: "Deniz Aydın",
                content: "Lothlórien! The Golden Wood sounds absolutely magical.",
                created_at: "2026-04-22T19:00:00Z",
                likes: 18,
            },
            {
                id: "cmt-6",
                author_id: "9",
                author_name: "Ayşe Koç",
                content: "Minas Tirith during the days of its glory. The White City must have been breathtaking.",
                created_at: "2026-04-22T19:30:00Z",
                likes: 14,
            },
        ],
        saves: 22,
    },
    {
        id: "post-4",
        community_id: "comm-3",
        community_name: "Dune Universe",
        author_id: "3",
        author_name: "Mehmet Kaya",
        author_role: "creator",
        content:
            "\"I must not fear. Fear is the mind-killer. Fear is the little-death that brings total obliteration.\" — This litany has genuinely helped me in stressful moments in real life. Has Dune changed how you think about anything?",
        created_at: "2026-04-22T10:00:00Z",
        likes: 55,
        comments: [
            {
                id: "cmt-7",
                author_id: "10",
                author_name: "Emre Yıldız",
                content: "The concept of the Kwisatz Haderach really made me think about destiny vs. free will in a new way.",
                created_at: "2026-04-22T11:00:00Z",
                likes: 9,
            },
        ],
        saves: 19,
    },
    {
        id: "post-5",
        community_id: "comm-4",
        community_name: "Crime & Thriller Book Club",
        author_id: "4",
        author_name: "Zeynep Arslan",
        author_role: "creator",
        content:
            "Just finished \"The Silent Patient\" by Alex Michaelides and WOW. That ending. I'm still processing it. No spoilers in comments please, but if you've read it — you know what I mean 😱",
        created_at: "2026-04-21T20:00:00Z",
        likes: 41,
        comments: [
            {
                id: "cmt-8",
                author_id: "11",
                author_name: "Fatma Erdoğan",
                content: "I literally gasped at the end! Such a well-constructed thriller.",
                created_at: "2026-04-21T21:00:00Z",
                likes: 15,
            },
        ],
        saves: 11,
    },
    {
        id: "post-6",
        community_id: "comm-6",
        community_name: "Sci-Fi Universe",
        author_id: "6",
        author_name: "Selin Çelik",
        author_role: "creator",
        content:
            "Started reading \"Project Hail Mary\" by Andy Weir and I can't put it down. If you loved The Martian, this is even better. The science is fascinating and the story is incredibly heartwarming. Highly recommend! ⭐⭐⭐⭐⭐",
        created_at: "2026-04-21T16:00:00Z",
        likes: 72,
        comments: [
            {
                id: "cmt-9",
                author_id: "12",
                author_name: "Hakan Polat",
                content: "Rocky is one of the best characters in all of sci-fi. I cried at the ending!",
                created_at: "2026-04-21T17:00:00Z",
                likes: 28,
            },
            {
                id: "cmt-10",
                author_id: "1",
                author_name: "Ahmet Yılmaz",
                content: "Amaze amaze amaze! 🎵 (IYKYK)",
                created_at: "2026-04-21T17:30:00Z",
                likes: 19,
            },
        ],
        saves: 25,
    },
    {
        id: "post-7",
        community_id: "comm-5",
        community_name: "Classic Literature Society",
        author_id: "5",
        author_name: "Can Öztürk",
        author_role: "creator",
        content:
            "Monthly reading assignment for May: \"Notes from Underground\" by Dostoevsky. It's short (under 150 pages) but incredibly dense. The unnamed narrator's existential crisis feels surprisingly modern. Discussion thread opens May 1st!",
        created_at: "2026-04-20T09:00:00Z",
        likes: 34,
        comments: [],
        saves: 18,
    },
    {
        id: "post-8",
        community_id: "comm-2",
        community_name: "Potterheads United",
        author_id: "7",
        author_name: "Burak Şahin",
        author_role: "member",
        content:
            "Just got the illustrated editions of the first three books and they are STUNNING. Jim Kay's artwork brings Hogwarts to life in ways I never imagined. Worth every penny for any collector! 📖✨",
        image_url: "https://images.unsplash.com/photo-1551269901-5c5e14c25df7?w=800&h=500&fit=crop",
        created_at: "2026-04-19T14:00:00Z",
        likes: 96,
        comments: [
            {
                id: "cmt-11",
                author_id: "2",
                author_name: "Elif Demir",
                content: "The illustrated Prisoner of Azkaban is my absolute favourite! The Boggart scene is incredible.",
                created_at: "2026-04-19T15:00:00Z",
                likes: 11,
            },
        ],
        saves: 44,
    },
];

// ─── Mock Recent Activity ───
export const MOCK_RECENT_ACTIVITY: RecentActivity[] = [
    {
        id: "act-1",
        user_id: "4",
        user_name: "Zeynep Arslan",
        action: "joined",
        target: "Lord of the Rings Lovers",
        timestamp: "3 min ago",
    },
    {
        id: "act-2",
        user_id: "6",
        user_name: "Selin Çelik",
        action: "posted in",
        target: "Sci-Fi Universe",
        timestamp: "5 min ago",
    },
    {
        id: "act-3",
        user_id: "7",
        user_name: "Burak Şahin",
        action: "liked a post in",
        target: "Potterheads United",
        timestamp: "12 min ago",
    },
    {
        id: "act-4",
        user_id: "8",
        user_name: "Deniz Aydın",
        action: "commented in",
        target: "Lord of the Rings Lovers",
        timestamp: "18 min ago",
    },
    {
        id: "act-5",
        user_id: "9",
        user_name: "Ayşe Koç",
        action: "joined",
        target: "Dune Universe",
        timestamp: "25 min ago",
    },
    {
        id: "act-6",
        user_id: "10",
        user_name: "Emre Yıldız",
        action: "created a community",
        target: "Turkish Literature Circle",
        timestamp: "1 hour ago",
    },
    {
        id: "act-7",
        user_id: "11",
        user_name: "Fatma Erdoğan",
        action: "joined",
        target: "Crime & Thriller Book Club",
        timestamp: "2 hours ago",
    },
    {
        id: "act-8",
        user_id: "12",
        user_name: "Hakan Polat",
        action: "posted in",
        target: "Classic Literature Society",
        timestamp: "3 hours ago",
    },
];

// ─── User's reading interests (for sidebar) ───
export const MOCK_USER_INTERESTS = [
    "Fantasy Reader",
    "Sci-Fi Enthusiast",
    "Classic Literature",
    "Mystery Lover",
    "Book Collector",
    "Philosophy",
];
